name: Deploy Azure Resources

on: 
 workflow_call:
            
jobs:

  build :
    runs-on: ubuntu-latest
    steps:
    
    - name: Create Security Group and Service Principal
      uses: azure/powershell@v1
      with:
        gname: ${{ secrets.AZ_GROUP_NAME }}
        spname: ${{ secrets.AZ_SP_NAME }}
        audience: ${{ secrets.AZ_FC_AUDIENCE }}
        issuer: ${{ secrets.AZ_FC_ISSUER }}
        name: ${{ secrets.AZ_FC_NAME }}
        subject:  ${{ secrets.AZ_FC_SUBJECT }}
        tenantid: ${{ secrets.AZURE_TENANT_ID }}
        
        inlineScript: |
         $ADgroupId = (Get-AzADGroup -DisplayName "$gname").Id
         $SPObjId = (Get-AzADServicePrincipal -ServicePrincipalName "$spname").Id
         $members = @()
         $members += (Get-AzADServicePrincipal -ObjectId $SPObjId).Id
         
         Connect-AZAccount -tenantid "$tenantid" 
         
         New-AzADGroup -DisplayName "$gname" -SecurityEnabled
         
         New-AzADServicePrincipal -DisplayName  "$spname"
         
         Add-AzADGroupMember -TargetGroupObjectId $ADgroupId -MemberObjectId $members
   
        azPSVersion: "latest"
    


 

       

