name: Deploy Azure Resources

on: 
 workflow_call:

env:
  gname: ${{ secrets.AZ_GROUP_NAME }}
  spname: ${{ secrets.AZ_SP_NAME }}
  tenantid: ${{ secrets.AZURE_TENANT_ID }}
 
  
jobs:

  build :
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az Module
      uses: azure/login@v1
      with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         allow-no-subscriptions: true
      
    
    - name: Create Security Group and Service Principal
      uses: azure/powershell@v1
      with:
        inlineScript: |
        
         ./Create-ADSGroup.ps1 -GroupDisplayName ${{ env.gname }} -TenantID ${{ env.tenandid }} -SPDisplayName ${{ env.spname }}
   
        azPSVersion: "latest"
    


 

       

