name: Deploy Azure Resources

on: 
 workflow_call:

env:
  gname: ${{ secrets.AZ_GROUP_NAME }}
  spname: ${{ secrets.AZ_SP_NAME }}
  tenantid: ${{ secrets.AZURE_TENANT_ID }}
  
jobs:

  build :
    runs-on: ubuntu-latest
    steps:
    
    - name: Create Security Group and Service Principal
      uses: azure/powershell@v1
      with:
        inlineScript: |
        
         Connect-AZAccount -tenantid $env:tenantid
         
         New-AzADGroup -DisplayName $env:gname -SecurityEnabled
         
         New-AzADServicePrincipal -DisplayName $env:spname
         
         $ADgroupId = (Get-AzADGroup -DisplayName $env:gname).Id
         $SPObjId = (Get-AzADServicePrincipal -ServicePrincipalName $env:spname).Id
         $members = @()
         $members += (Get-AzADServicePrincipal -ObjectId $SPObjId).Id
         
         Add-AzADGroupMember -TargetGroupObjectId $ADgroupId -MemberObjectId members$
   
        azPSVersion: "latest"
    


 

       

