name: Deploy Azure Resources

on: 
 workflow_call:
            
jobs:

  build :
    runs-on: ubuntu-latest
    steps:
    
    - name: Create Security Group and Service Principal
      uses: azure/powershell@v1
      env:
        gname: ${{ secrets.AZ_GROUP_NAME }}
        spname: ${{ secrets.AZ_SP_NAME }}
        tenantid: ${{ secrets.AZURE_TENANT_ID }}
        
        inlineScript: |
        
         Connect-AZAccount -tenantid "$env:tenantid" 
         
         New-AzADGroup -DisplayName "$env:gname" -SecurityEnabled
         
         New-AzADServicePrincipal -DisplayName  "$env:spname"
         
         $ADgroupId = (Get-AzADGroup -DisplayName "$env:gname").Id
         $SPObjId = (Get-AzADServicePrincipal -ServicePrincipalName "$env:spname").Id
         $members = @()
         $members += (Get-AzADServicePrincipal -ObjectId "$env:SPObjId").Id
         
         Add-AzADGroupMember -TargetGroupObjectId "$env:ADgroupId" -MemberObjectId "$env:members"
   
        azPSVersion: "latest"
    


 

       

