name: Deploy Azure Resources

permissions:
  id-token: write
  contents: write
    
env:

 gname: ${{ secrets.AZ_GROUP_NAME }}
 spname: ${{ secrets.AZ_SP_NAME }}
 
on: 
 workflow_call:
 
jobs:

  build :
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.6.0
      
    - name: Login via Az Module
      uses: azure/login@v1
      with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANTID }}
         allow-no-subscriptions: true
         enable-AzPSSession: true 
     
    - name: Create New AZ Security Group     
      run: New-AZADGroup -DisplayName "${{ env.gname }}" -SecurityEnabled
    - name: Create new Service Principal     
      run: New-AZADServicePrincipal -DisplayName "${{ env.spname }}"
    - name: Add Service Principal to Security Group
      run : |
         Connect-AZAccount -tenantid ${{ secrets.AZURE_TENANTID }}
         $SPOjbID = (Get-AZADServicePrincipal -ServicePrincipalName "${{ env.spname }}").Id
         $members += @()                            #can add other members
         $members += (Get-AZADServicePrincipal -ObjectId $SPObjID).Id
         $ADgroupId = (Get-AzADGroup -DisplayName "GroupDisplayName").Id
         Add-AZADGroupMember -TargetGroupObjectId $ADgroupId -MemberObjectId $members
       
      

    


 

       

