name : Deploy

permissions:
  id-token: write
  contents: write


on:
  workflow_call:
    inputs:
      containertag:
        description: 'GitHub Container Tag'
        required: true
        type: string
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      containertag:
        description: 'GitHub Container Tag'
        required: true
        type: string
      environment:
        type: environment
        required: true


concurrency: ${{ inputs.environment }}

    
jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   
      - name: ACR Login
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}          
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          images: '${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.AZURE_CONTAINER_IMAGE_NAME }}:${{ inputs.containertag }}'
      - name: Create GitHub Release
        if: ${{inputs.environment == 'Production' }}
        run: "gh release create ${{ inputs.containertag }} --generate-notes"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
