name: Deploy Azure Resources

on: 
 workflow_call:
  inputs:
   environment:
    type: string
    required: true
            
jobs:

  build :
    runs-on: ubuntu-latest
    steps:
    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        gname: ${{ secrets.AZ_GROUP_NAME }}
        spname: ${{ secrets.AZ_SP_NAME }}
        audience: ${{ secrets.AZ_FC_AUDIENCE }}
        issuer: ${{ secrets.AZ_FC_ISSUER }}
        name: ${{ secrets.AZ_FC_NAME }}
        subject:  ${{ secrets.AZ_FC_SUBJECT }}
        tenantid: ${{ secrets.AZURE_TENANT_ID }}
        
        inlineScript: |
         Connect-AZAccount -tenantid "$tenantid" 
         ./Create-NewAzureEnvironment.ps1
        azPSVersion: "latest"
        
        

